name = "shimmer"
version = "0.0.4"

licences = ["Apache-2.0"]
description = "A Gleam library for interacting with the Discord API"
repository = { type = "github", user = "HarryET", repo = "shimmer" }
links = [
    { title = "Website", href= "https://hexdocs.pm/shimmer" },
    { title = "Sponsor", href = "https://github.com/sponsors/HarryET" }
]

[dependencies]
gleam_stdlib = "~> 0.25"
gleam_hackney = "~> 0.2"
gleam_json = "~> 0.5"
gun = "> 1.3.0 and < 3.0.0"
gleam_http = "~> 3.1"
certifi = "~> 2.9"
gleam_otp = "~> 0.5"
gleam_erlang = "~> 0.17"
gleam_bitwise = "~> 1.2"

[dev-dependencies]
gleeunit = "~> 0.5"
